### ISSUE TITLE
Class Loader prints DEBUG level log then throws

### ISSUE THREAD

**Issue by IanTheEngineer** [ros/pluginlib#119]
Right I'm debugging an issue in ROS Kinetic where pluginlib is failing to find/load my plugins. If it turns out to be an issue that could affect other users, I'll create an Issue/PR for it. 

In the mean time, I've encountered a more direct issue: I am not seeing much output when the pluginlib fails to load a class. In particular, after setting ROS_LOGGER level to DEBUG, I ran into [this DEBUG output](https://github.com/ros/pluginlib/blame/kinetic-devel/include/pluginlib/class_loader_imp.hpp#L607-L616) which seems like it should be  a ROS_ERROR_NAMED as it throws:
```
template<class T>
void ClassLoader<T>::loadLibraryForClass(const std::string & lookup_name)
/***************************************************************************/
{
  ClassMapIterator it = classes_available_.find(lookup_name);
  if (it == classes_available_.end()) {
    ROS_DEBUG_NAMED("pluginlib.ClassLoader", "Class %s has no mapping in classes_available_.",
      lookup_name.c_str());
    throw pluginlib::LibraryLoadException(getErrorStringForUnknownClass(lookup_name));
}
```
It is possible that the `pluginlib::LibraryLoadException` should be printing a more user-friendly error, but I am not seeing any output in my logfile after the DEBUG print, so that might actually be the core of the issue.

**Comment by mikaelarguedas** [comment]
thanks @IanTheEngineer for reporting (and the patience).
It looks like pluginlib is printing only debug messages when throwing.
There isn't much context about why these are logged with a DEBUG severity rather than ERROR in the [commit introducing them](https://github.com/ros/pluginlib/commit/dca612adad2aa0a4d7acfdcaa31b65409d7b8ea7). I would expect that it is for users to be able to catch such exception without having important severity in their logs.
Edit: that's what pluginlib_tutorials do for example: https://github.com/ros/common_tutorials/blob/indigo-devel/pluginlib_tutorials/src/polygon_loader.cpp

> It is possible that the pluginlib::LibraryLoadException should be printing a more user-friendly error, but I am not seeing any output in my logfile after the DEBUG print, so that might actually be the core of the issue.

Do you mean that a more descriptive message printed to debug would be satisfactory ? or that you would like all messages logges when trhowing to be logged with a higher severity?

**Comment by clalancette** [comment]
There's been no response on this in many years, so going ahead and closing this one out.  Feel free to reopen if you are still having problems.
