### ISSUE TITLE
Rospack not detecting my Plugin

### ISSUE THREAD

**Issue by IffatJamil** [ros/pluginlib#172]
The Rospack is not showing my custom plugin. I did add dependencies on nav_core i.e;
<build_depend>nav_core</build_depend>
<run_depend>nav_core</run_depend>
but it still didn't resolve the issue, still Rospack is unable to show my custom plugin.

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
