### ISSUE TITLE
Question about how to export plugin.xml files

### ISSUE THREAD

**Issue by JaehyunShim** [ros/pluginlib#198]
Hi @sloretz 

I would like to ask a question about how to export plugin.xml files. I am currently using Ubuntu 20.04, ROS2 Foxy version.

It seems, in ROS2, you should add **_pluginlib_export_plugin_description_file(plugin_file_name.xml)_** in CMakeLists.txt and build the package, but you don't have to export anything in your package.xml file (which is different from this test [code](https://github.com/ros/pluginlib/blob/foxy/pluginlib/test/test_package.xml) you uploaded last month). What is the difference and what is the right way of doing it (exporting plugin.xml)? If there is any instruction for ROS2 like this [one](http://wiki.ros.org/pluginlib) which was for ROS1, it would be really helpful.

Any help or advice would be appreciated,
Ryan

**Comment by sloretz** [comment]
> but you don't have to export anything in your package.xml file (which is different from this test code you uploaded last month

I'm not sure if the entry in the `<export>` section of the `package.xml` file is still needed in ROS 2. It looks like that `package.xml` [hasn't been changed since 2018](https://github.com/ros/pluginlib/blob/foxy/pluginlib/test/test_package.xml), so it may be out of date.

> If there is any instruction for ROS2 like this one which was for ROS1, it would be really helpful.

There are some instructions in the documentation of the CMake macro `pluginlib_export_plugin_description_file()`

https://github.com/ros/pluginlib/blob/a7468c9e2e11ac17025a645030143b2fc2931ece/pluginlib/cmake/pluginlib_export_plugin_description_file.cmake#L22-L81

I don't see any tutorials for `pluginlib` in ROS 2 :( https://index.ros.org/doc/ros2/Tutorials/#tutorials If you're willing to contribute a tutorial that would be very helpful :)


If you have further questions, I'd recommend opening them on https://answers.ros.org.
