### ISSUE TITLE
Plugins cannot be loaded on debug builds

### ISSUE THREAD

**Issue by muratsevim** [ros/pluginlib#20]
If the workspace that contains the `pluginlib` and `class_loader` packages are compiled with `catkin_make -DCMAKE_BUILD_TYPE="Debug"` command, the plugins cannot be loaded.

For example trying to load `image_transport/raw_pub` plugin produces the following logs

```
[DEBUG] [1379221062.565758000]: Attempting to create managed instance for class image_transport/raw_pub.
[DEBUG] [1379221062.565798000]: Class image_transport/raw_pub maps to library lib/libimage_transport_plugins in classes_available_.
[DEBUG] [1379221062.671369000]: Iterating through all possible paths where lib/libimage_transport_plugins could be located...
[DEBUG] [1379221062.673023000]: Checking path /Users/murat/ros/common_ws/devel/lib/lib/libimage_transport_pluginsd.dylib 
[DEBUG] [1379221062.673180000]: Checking path /Users/murat/ros/common_ws/devel/lib//libimage_transport_pluginsd.dylib 
[DEBUG] [1379221062.673327000]: Checking path /Users/murat/ros/core_ws/devel/lib/lib/libimage_transport_pluginsd.dylib 
[DEBUG] [1379221062.673495000]: Checking path /Users/murat/ros/core_ws/devel/lib//libimage_transport_pluginsd.dylib 
[DEBUG] [1379221062.674935000]: No path could be found to the library containing image_transport/raw_pub.
[ WARN] [1379221062.675168000]: Failed to load plugin image_transport/raw_pub, error string: Could not find library corresponding to plugin image_transport/raw_pub. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
```

I figured this is because the debug builds are linked against debug version of Poco library, which uses `d.dylib` suffix for shared libraries on `OS X`. On the other hand all plugin libraries have `.dylib` suffix even if they are compiled using `Debug` build type.

`Poco 1.4.6p1` is installed on the system via `Homebrew`

I occasionally need to build ros packages using `Debug` build type to debug other problems. This issue comes up whenever I do that.

**Comment by mirzashah** [comment]
@muratsevim your explanation makes sense, i don't have enough mac experience to give you a solution. however i know a super genius who does. @wjwwood - do you have any insights? :)

**Comment by mirzashah** [comment]
@muratsevim can you not install the debug versions of the library via homebrew? if not, the only option i can think of is to build a debug version of poco

ooh another really gross solution would be to symlink the release versions with the debug library names. you won't be able to step the debugger into poco world, but should let you build debug versions of your own code.

is there a way to change lflags so that you link against release version of poco instead of debug version?

**Comment by muratsevim** [comment]
Apparently `PocoConfig.cmake` file in `class_loader` chooses debug version of poco libraries if the build type is `Debug`. As a workaround I can modify it to always use the release versions. However, this does not feel like the right solution because when building for debugging it makes sense to use debug version of the linked libraries if they are available.

By the way, I think the issue is not specific to `OS X`. I haven't tested on `Linux` but the poco source code suggests its debug libraries will use `d.so` for suffixes of shared libraries. I wonder how common it is to append `d` to the library name for debug builds. I haven't seen any library (other than poco) that does this.

**Comment by mirzashah** [comment]
Hmm interesting. I'm actually not sure what the conventions are myself on linux regarding debug versions of libraries. I'm not sure if it's convention to include debug versions of libraries in dev packages. I know on Windows it's  common to denote debug libraries with a "d" or "_d" suffix...but that doesn't help us here. It's very rare to have to debug a third party package so usually you don't care if it's release/debug. In the cases that I've had to do this in the past, I always build from source with debug flags.

We can change the PocoConfig.cmake file if necessary.  However, it should follow conventions of Linux, MacOS, and Windows. We can add in directives specific to MacOS in the .cmake file as well.

@dirk-thomas @tfoote Do you guys have any insights regarding the nature of debug library naming conventions on Ubuntu? Would you please advise on how to proceed regarding this issue, thanks!

**Comment by tfoote** [comment]
What I'm most familiar is that you build with debug and then strip the debug symbols out in the debian process to be packaged into *-dbg package.  Thus the library should work whether or not the debug symbols are present and gdb knows how to cross reference the dbg files.  

And if you're building from source, you just compile the debug symbols into the libraries.

**Comment by wjwwood** [comment]
I do not think it makes sense to have different names for debug and non-debug libraries, though it maybe the preference/style of Windows to do that (I don't know). It is not recommended on OS X as far as I know. I have not run into this issue on my machine, but I can try to reproduce it with a little more information.

@muratsevim can you setup a simple example (Set of packages to build with Debug on) such that I can reproduce it?

**Comment by muratsevim** [comment]
I can produce this error with the following steps:

```
mkdir testws
cd testws
rosinstall_generator pluginlib --rosdistro hydro --deps --exclude console_bridge > test.rosinstall
wstool init src test.rosinstall
src/catkin/bin/catkin_make -DCMAKE_BUILD_TYPE=Debug run_tests
```

This will create a workspace with `pluginlib` and all required packages, then it will run the tests. You will see `PluginlibTest.workingPlugin` test fails.

Some notes:
- `console_bridge` is excluded from the workspace because it is installed as a system dependency on my system.
- You might need to add `target_link_libraries(test_plugins tinyxml ${catkin_LIBRARIES} ${Boost_LIBRARIES})` line to `pluginlib/CMakeLists.txt` file to fix linking errors.

**Comment by mirzashah** [comment]
@wjwwood @tfoote What you guys are saying makes sense -- in that case I would recommend modifying the cmake package config file to use the same target names for debug and release libraries.

**Comment by wjwwood** [comment]
I just ran into this again. On my machine, when `class_loader` and `pluginlib` are built with build type Debug, my `rviz` cannot locate plugins:

```
[DEBUG] [1398842515.000109000]: Attempting to create UNMANAGED instance for class rviz/Orbit.
[DEBUG] [1398842515.000203000]: Class rviz/Orbit maps to library libdefault_plugin in classes_available_.
[DEBUG] [1398842515.058778000]: Iterating through all possible paths where libdefault_plugin could be located...
[DEBUG] [1398842515.058922000]: Checking path /tmp/rviz_ws/devel/lib/libdefault_plugind.dylib
[DEBUG] [1398842515.059005000]: Checking path /tmp/rviz_ws/devel/lib/libdefault_plugind.dylib
[DEBUG] [1398842515.059058000]: Checking path /tmp/rviz_ws/underlay/install/lib/libdefault_plugind.dylib
[DEBUG] [1398842515.059116000]: Checking path /tmp/rviz_ws/underlay/install/lib/libdefault_plugind.dylib
[DEBUG] [1398842515.059182000]: Checking path /tmp/rviz_ws/src/rviz/libdefault_plugind.dylib
[DEBUG] [1398842515.059239000]: Checking path /tmp/rviz_ws/src/rviz/libdefault_plugind.dylib
[DEBUG] [1398842515.059293000]: No path could be found to the library containing rviz/Orbit.
[ERROR] [1398842515.059378000]: PluginlibFactory: The plugin for class 'rviz/Orbit' failed to load.  Error: Could not find library corresponding to plugin rviz/Orbit. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
```

As you can see it is looking for `/tmp/rviz_ws/src/rviz/libdefault_plugind.dylib` which has an extra `d` before the `.dylib`. The file `/tmp/rviz_ws/src/rviz/libdefault_plugin.dylib` exists on my machine.

This appears to be because of how `class_loader` uses `Poco`:

https://github.com/ros/class_loader/blob/hydro-devel/src/class_loader.cpp#L44

According to `Poco` (http://www.appinf.com/docs/poco/Poco.SharedLibrary.html):

> suffix static
> static std::string suffix();
> Returns the platform-specific filename suffix for shared libraries (including the period).
> In debug mode, the suffix also includes a "d" to specify the debug version of a library.

I think that `pluginlib` should be made more intelligent here:

https://github.com/ros/pluginlib/blob/indigo-devel/include/pluginlib/class_loader_imp.h#L238-261

Such that it checks for the extra `d` and if it finds in the suffix returned by `class_loader` then it should try paths both with and without the `d`.

@esteve this is a pretty important bug to fix, can you take a look at it soonish?

**Comment by esteve** [comment]
@wjwwood Sure, no problem.

**Comment by mantkiew** [comment]
@esteve Today, I just stumbled upon an edge case here: 
1. have a package P release build sourced, which has `libP_nodelet.so`
2. have a catkin workspace with a debug build of the same package P, which has `devel/lib/libP_nodelet-d.so`.

When debugging P node which loads the P_nodelet, it always loads `libP_nodelet.so` instead of `devel/lib/libP_nodelet-d.so` from the catkin workspace! It really tripped me hard. The workaround I have on linux is to manually create a symlink 
```
devel/lib$ ln -s libP_nodelet-d.so libP_nodelet.so
```
Then debugging works and the `devel/lib/libP_nodelet-d.so`  is loaded via the symlink. 

I wanted to post this because it can trip other people. It would be good to maybe load the `-d.so` first instead of whatever `.so` can be found first.
