### ISSUE TITLE
Load plugin where base class exists in another project

### ISSUE THREAD

**Issue by jlack1987** [ros/pluginlib#53]
I'm having some trouble loading a plugin and decided to open an issue to see if it's even possible. I am creating `package_B` where i'm creating a class that implements a plugin base class that exists in `package_A`. 

Also, somewhere in `package_A`, they call `loader->createInstance(plugin_type)`. When plugin_type equals the plugin i've created in `package_B`, it fails saying the plugin doesn't exist. But when the plugin type is one of the plugins created/exported from `package_A`, it works just fine. I feel like maybe pluginlib isn't built to do what i'm trying to make it do. Thoughts?

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
